# vim: sts=2 sw=2 ai

linux_task:
  container:
    image: gcc:latest

  setup_script:
    - git submodule update --init shaders/SPIRV-Cross
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install meson gettext libsdl2-dev libgtk-3-dev libminizip-dev portaudio19-dev glslang-dev

  compile_script:
    - meson build gtk --buildtype=release --strip
    - ninja -j2 -C build

  package_script:
    - mkdir snes9x
    - cp -ar build/snes9x-gtk README.md LICENSE docs data gtk/AUTHORS snes9x/
    - tar -caf "snes9x-${CIRRUS_CHANGE_IN_REPO}.txz" snes9x

  build_artifacts:
    path: "snes9x-${CIRRUS_CHANGE_IN_REPO}.txz"


macOS_task:
  osx_instance:
    image: mojave-xcode

  compile_script:
    - xcodebuild -project macosx/snes9x.xcodeproj -target Snes9x -configuration Release build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

  package_script:
    - mkdir snes9x
    - cp -R macosx/build/Release/Snes9x.app macosx/docs README.md LICENSE snes9x/
    - zip -r "snes9x-${CIRRUS_CHANGE_IN_REPO}.zip" snes9x

  build_artifacts:
    path: "snes9x-${CIRRUS_CHANGE_IN_REPO}.zip"

